baseURL = 'https://shumikama.github.io/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'shumikama2'
timeZone = "Asia/Tokyo"
theme = 'PaperMod'
googleAnalytics = "G-WQN2DY6SZJ"


[params.profileMode]
enabled = true
title = "Naonari"
subtitle = "begleri & kendama player"
imageUrl = "profile.png"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
  name = "Links"
  url = "/links/"

[[params.profileMode.buttons]]
  name = "Gallery"
  url = "/gallery/"


[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/1021z_ani/"

[[params.socialIcons]]
name = "mastodon"
url = "https://fedibird.com/@zani"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/watch?v=kse3zT1TmSA"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/show/1O1CuKaReDUQD6y9enUqMd"


[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 20


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
title = "shumikama2"
description = "ベグレリ・けん玉プレイヤーの個人サイト"
DateFormat = '2006/01/02'
defaultTheme = "auto"
images = [ "logo.png" ]
ShowBreadCrumbs = false
